Wprowadzenie do języka R

<h2> Wprowadzenie</h2>

**R** to język programowania i środowisko do obliczeń statystycznych oraz analizy danych, rozwijany od lat 90. XX wieku. Powstał jako implementacja koncepcji języka S i jest obecnie utrzymywany w ramach projektu <a href="https://www.r-project.org">R Project for Statistical Computing</a>. **R** jest oprogramowaniem open source i posiada bardzo rozbudowany ekosystem pakietów (CRAN, Bioconductor), co czyni go jednym z kluczowych narzędzi w analizie danych naukowych.

Główne zastosowania języka **R**:

Statystyka i modelowanie statystyczne
R oferuje szeroki zakres metod: od klasycznej regresji liniowej i testów hipotez, przez modele mieszane i analizy wielowymiarowe, po zaawansowane modele bayesowskie. Jego składnia i struktura danych (wektory, ramki danych, listy) są zaprojektowane z myślą o analizie statystycznej.

Data science i eksploracja danych
Dzięki pakietom takim jak dplyr, data.table czy tidyr, **R** umożliwia efektywne przetwarzanie i transformację danych. Jest szeroko wykorzystywany do eksploracyjnej analizy danych, w tym wizualizacji.

Wizualizacja danych
**R** jest szczególnie ceniony za wysoką jakość i elastyczność wizualizacji. 

Bioinformatyka i analiza danych medycznych
Dzięki projektowi <a href="https://www.bioconductor.org">Bioconductor R</a> pozostaje jednym z dominujących narzędzi w analizie danych genomowych, transkryptomicznych i proteomicznych. W środowisku akademickim i badawczym jest to wciąż standard.

Ekonometria i nauki społeczne
**R** jest szeroko stosowany w ekonomii, socjologii i politologii do modelowania danych panelowych, analiz regresyjnych i symulacji. W wielu czasopismach naukowych publikacje opierają się na analizach przeprowadzonych w **R**.

Raportowanie i reproducibility
Narzędzia takie jak **R** Markdown umożliwiają łączenie kodu, wyników i opisu analizy w jednym, reprodukowalnym dokumencie (HTML, PDF, Word). To kluczowe w badaniach naukowych i analizach biznesowych wymagających audytowalności.

Mimo rosnącej popularności języków takich jak Python w obszarze ogólnego data science i uczenia maszynowego, **R** nadal utrzymuje silną pozycję tam, gdzie kluczowe są zaawansowane metody statystyczne, wysoka jakość wizualizacji oraz rygor naukowy analizy danych.

<h2> Cel laboratoriów </h2>

Celem tego laboratorium jest poznanie składni języka **R**. W szczególności przedstawione zostaną:

- sposoby wczytywania danych
- najważniejsze typy danych dostępne w **R**
- pętle i instrukcje warunkowe
- sposoby tworzenia funkcji

Zadania mają na celu jedynie przyzwyczajenie się do języka. Zadania w instrukcji są proste do wykonania. Korzystanie z narzędzi do generowania kodu mija się z celem.

<h2> Praca z danymi </h2>

Skoro nasze narzędzie ma umożliwić łatwą analizę danych, to musimy zacząć od ich wczytania. W tym celu, w zależności o rodzaju plików, mamy do dyspozycji już w samym bazowym **R** kilka funkcji:
- `read.table`,
- `read.csv`,
- `read.csv2`,
- `read.delim`,
- `read.delim2`.

Wszystkie one wykonują to samo działanie na najistotniejsze różnica leży w wartościach domyślnych argumentów tych funkcji. Wczytując dane z pliku najważniejsze parametry, które należy wziać pod uwagę to:

- `header` - określa czy plik zawiera nagłówek (pierwszy wiersz z nazwami kolumn). Dopuszczalne wartości to `TRUE` oraz `FALSE`.
- `sep` - znak, który rozdziela kolumny w pliku (najczęściej `','`, `';'` lub `'\t'`).
- `dec` - znak używany w zapisie liczb zmiennoprzecinkowych (najczęściej `'.'` lub `','`).
- `encoding` - pozwala określić kodowanie pliku (najczęściej  `Latin-1` lub `UTF-8`).

Domyśle wartości dla powyższych funkcji to:
- `read.table(file,  header = FALSE, sep = "",   dec = ".", ...)`
- `read.csv(file,    header = TRUE,  sep = ",",  dec = ".", ...)`
- `read.csv2(file,   header = TRUE,  sep = ";",  dec = ",", ...)`
- `read.delim(file,  header = TRUE,  sep = "\t", dec = ".", ...)`
- `read.delim2(file, header = TRUE,  sep = "\t", dec = ",", ...)`

Funkcje te pozwalają określić jeszcze szereg innych informacji o pliku. Proszę przejrzeć dostępne parametry na przykładzie dokumentacji funkcji <a href="https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/read.table">read.table</a>.

Pierwszym argumentem jest `file` i określa on ścieżkę do pliku. Najczęściej nie używa się pełnych ścieżek, a wskazuje plik z katalogu roboczego. Aktualny katalog roboczy można określi poleceniem `getwd()`.

In [1]:
getwd()

[1] "c:/Users/User/Statistics-in-Artificial-Intelligence-and-Data-Analysis"

<h5>Uwaga!</h5>
Jeżeli Twoje środowisko uruchomione jest w kontenerze dockera, to pamiętaj, że ścieżka ta odnosi się do systemu zainstalowanego w kontenerze. Żeby wczytać własne dane musisz załadować je osobno, np. z poziomu Jupytera, lub korzystając z katalogu wymiany określonego podczas tworzenia kontenera.

Warto tu zwrócić uwagę jeszcze na dwie funkcje:
- `dir` - wyświetla zawartość bieżącego folderu roboczego;
- `setwd` - pozwala zmienić bieżący folder roboczy.

In [2]:
dir()

[1] "R - wprowadzenie.ipynb"

Zadanie:

Utwórz nowy folder **data** (ręcznie - bez korzystania z R), a następnie ustal go jako bieżący katalog roboczy.

In [3]:
setwd("data/")

In [4]:
getwd()

[1] "c:/Users/User/Statistics-in-Artificial-Intelligence-and-Data-Analysis/data"

Zadanie: 

Pobierz pliki tekstowe do katalogu data, a następnie wyczytaj każdy z nich dwukrotnie. Raz korzystając z funkcji read.table, a drugi raz dobierając funkcję o jak najlepszych parametrach domyślnych. Wczytane wartości przypisz do zmiennych o nazwach takich samych jak nazwa pliku (bez rozszerzenia).

In [ ]:
{}

In [ ]:
d1 = read.table('d1.csv',  header = FALSE, sep = "",   dec = ".")

Po wczytaniu danych warto sprawdzić, jak wyglądają wczytane wartości oraz upewnić się, że wszystko jest tak jak chcieliśmy.

In [ ]:
d1

Wypisywanie wszystkich wartości jest w wielu przypadkach niepraktyczne. Zamiast tego używa się specjalnych funkcji zwracających informacje o wczytanych danych:
- `str`: zwraca informacje o liczbie obserwacji, liczbie kolumn, typie zmiennych w poszczególnych kolumnach oraz pokazuje przykładowe wartości.
- `head`: zwraca kilka początkowych wierszy z wczytanych danych
- `tail`: zwraca kilka końcowych wierszy z wczytanych danych, szczególne przydatne w analizie szeregów czasowych.
- `summary`: zwraca podstawowe statystyki opisowe wczytanych zmiennch.

In [ ]:
str(d1)

In [ ]:
head(d1)

In [ ]:
summary(d1)

<h3>Zapis danych do pliku</h3> 

Wartość z dowolnej zmiennej tabelarycznej możemy zapisać z użyciem funkcji `write.csv`.

In [ ]:
write.csv(summary(d1),"output.csv")

<h2> Typy Zmiennych </h2>

Zobaczmy teraz jak naszą zmienną widzi **R**. Możemy to zobaczyć z perspektywy "wysokopoziomowej" (`class`) lub "niskopoziomowe" (`typeof`).

In [ ]:
class(d1)

Widzimy, że wczytane dane są typu `data.frame`. Jest to jedne z typów danych którym będzie dla nas wygodny, by manipulować danymi. Za chwilę przyjrzymy mu się bliżej. Sprawdźmy jeszcze wynik funkcji `typeof`.

In [ ]:
typeof(d1)

Widzimy wynik `list`. Jest tak dlatego, gdyż "niskopoziomowo" `data.frame` to jest wewnętrznie listą kolumn. Nie wszystkie typy mają "wysokopoziomowe" otoczenie. Poniżej tabela pokazująca jak rzutowane są wybrane typy.

| Obiekt w R                         | typeof()       | class()             |
|-----------------------------------|---------------|--------------------|
| `5`                                | "double"      | "numeric"          |
| `5L`                               | "integer"     | "integer"          |
| `TRUE`                             | "logical"     | "logical"          |
| `"tekst"`                           | "character"   | "character"        |
| `1+2i`                              | "complex"     | "complex"          |
| `factor(c("a","b"))`                | "integer"     | "factor"           |
| `data.frame(a=1:3, b=4:6)`         | "list"        | "data.frame"       |
| `matrix(1:6, nrow=2)`              | "integer"/"double" | "matrix"      |
| `list(1, "a", TRUE)`                | "list"        | "list"             |
| `NULL`                              | "NULL"        | "NULL"             |

Zmienne typu `double`, `integer`, `logical`, `character`, `complex`, `list` i `NULL` nie wymagają chyba komentarza. Warto może jedynie podkreślić, że w **R** liczby domyślnie traktowane są jako double i jeśli chcemy byłby były widziane jako inty to musimy po wartości postawić **L**. Poza poznanym już `data.frame`-mem widzimy też `c`, `matrix` oraz `factor`.

<h3>c - wektory</h3>

`c`: to funckja tworząca wektory. Może przyjąć wiele wartości, ale wszystkie muszą być tego samego typu. Podczas tworzenia można łączyć różne typy, ale finalnie zostaną one rzutowane do jednego.

In [5]:
var = c(1,2,3)
class(var)
typeof(var)

[1] "numeric"

[1] "double"

In [6]:
var = c(1L,2L,3L)
class(var)
typeof(var)

[1] "integer"

[1] "integer"

In [7]:
var = c(1L,2,3)
class(var)
typeof(var)

[1] "numeric"

[1] "double"

In [8]:
var = c('a',2,TRUE)
class(var)
typeof(var)
var

[1] "character"

[1] "character"

[1] "a"    "2"    "TRUE"

Wektory można łatwo łączyć.

In [9]:
var1 = c(1,2,3)
var2 = c(4,5,6)
var = c(var1, var2)
var

[1] 1 2 3 4 5 6

Długość wektra odczytujemy funkcją `length`.

In [10]:
length(var)

[1] 6

Odwoływać się do składowych wektora możemy po indeksach.

In [11]:
var[1]

[1] 1

**Uwaga!**

W **R** indeksujemy od 1.

Możemy odwoływać się poprzez określanie zakresów.

In [12]:
var[1:5]

[1] 1 2 3 4 5

Możemy odwoływać się poprzez wektor indeksów.

In [13]:
var = c('a', 'b', 'c', 'd', 'e', 'f')
var[c(2,4)]

[1] "b" "d"

Możemy odwoływać się poprzez maski.

In [14]:
var = c(1,20, 3, 40, 5)
var[var > 10]

[1] 20 40

<h3> matrix - macierze</h3> 

Typ `matrix` przeznaczony jest do przechowywania dwuwymiarowych tablic liczb.

In [15]:
m = matrix(1:6, nrow=2)
m

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

Aby odwołać się do konkretnego wiersza wystarczy podać jego indeks i przecinek.

In [16]:
m[1,]

[1] 1 3 5

Odwołanie do kolumny wykonujemy analogicznie podając drugi argument.

In [17]:
m[,2]

[1] 3 4

Warunki możemy łączyć i ograniczać.

In [18]:
m[1,c(1,3)]

[1] 1 5

Funkcja `length` zwraca liczbę elementów w macierzy.

In [19]:
length(m)

[1] 6

Aby uzyskać liczbę wierszy i kolumn stosujemy funkcje `dim`, albo jeśli interesuje nas tylko jedna z tych wartości, to `nrow` i `ncol`.

In [20]:
dim(m)
nrow(m)
ncol(m)

[1] 2 3

[1] 2

[1] 3

Poza standardowymi operacjami: dodawania (+), odejmowania(-), mnożenia element po elemencie(*), dzielenia element po elemencie (/) i potęgowania (^)

In [21]:
A <- matrix(1:4, 2)
B <- matrix(5:8, 2)
print(A)
print(B)

     [,1] [,2]
[1,]    1    3
[2,]    2    4
     [,1] [,2]
[1,]    5    7
[2,]    6    8

In [22]:
print(A+B)

     [,1] [,2]
[1,]    6   10
[2,]    8   12

In [23]:
print(A-B)

     [,1] [,2]
[1,]   -4   -4
[2,]   -4   -4

In [24]:
print(A*B)

     [,1] [,2]
[1,]    5   21
[2,]   12   32

In [25]:
print(A/B)

          [,1]      [,2]
[1,] 0.2000000 0.4285714
[2,] 0.3333333 0.5000000

In [26]:
print(A^2)

     [,1] [,2]
[1,]    1    9
[2,]    4   16

Warto również zwrócić uwagę na działanie mnożenia macierzy przez macierz (%*%).

In [27]:
print(A %*% B)

     [,1] [,2]
[1,]   23   31
[2,]   34   46

Poza tym dostępne są typowe operacje na macierzach:

In [28]:
#Wartości z przekatnej
diag(A)

[1] 1 4

In [29]:
#transpozycja macierzy
print(t(A))

     [,1] [,2]
[1,]    1    2
[2,]    3    4

In [30]:
# suma wierszami
rowSums(A)

[1] 4 6

In [31]:
# suma kolumnami 
colSums(A)

[1] 3 7

In [32]:
#wyznacznik macierzy
det(A)

[1] -2

In [33]:
#macierz odwrotna
A_inv = solve(A)
print(A_inv)

     [,1] [,2]
[1,]   -2  1.5
[2,]    1 -0.5

In [34]:
print(A_inv %*% A)

     [,1] [,2]
[1,]    1    0
[2,]    0    1

W powyższych przykładach wykorzystano funkcję `print`, żeby poprawić czytelność wyników.

In [35]:
zm = c(1,2,3)
zm = c("a","b")

Zadanie:

1. Utwórz macierz A o wymiarach 3×3, zawierającą liczby od 1 do 9.

2. Następnie wyświetl:

a. drugi wiersz,

b. trzecią kolumnę,

c. element z wiersza 2 i kolumny 3.

3 .Oblicz:

i. sumy wierszy,

ii. średnie kolumn,

iii. ślad macierzy,

4. Wypisz wymiary macierzy

5. Sprawdź, czy macierz jest odwracalna. Jeśli tak, to oblicz macierz odwrotną (jeśli nie, wyjaśnij dlaczego).

In [ ]:
A <- matrix(1:9, nrow=3)
print(A)
print(A[2,])
print(A[,3])
print(A[2,3])

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[1] 2 5 8
[1] 7 8 9
[1] 8

In [50]:
print(rowSums(A))
print(colSums(A))
print(colSums(A) / nrow(A))

print(sum(diag(A)))
print(dim(A))

[1] 12 15 18
[1]  6 15 24
[1] 2 5 8
[1] 15
[1] 3 3

In [55]:
is_square <- nrow(A) == ncol(A)
determinant <- det(A)

print(determinant)

if (is_square && determinant != 0) {
  A_inv = solve(A)
} else {
  A_inv = NULL
}
print(A_inv)

[1] 0
NULL

<h3>factor - zmienne kategoryczne</h3>

Typ `factor` przeznaczony jest dla danych kategorycznych. Opcjonalnie pozwala wprowadzić porządek pomiędzy wartościami nominalnymi. Jego działanie można intuicyjne interpretować jak działanie słownika w Pythonie, który tłumaczy wartości nominalne na odpowiedni indeks. Działanie na intach pozwala przyśpieszyć obliczenia.

In [56]:
#Przykładowy zbiór danych
ocena <- factor(c("niska", "średnia", "wysoka", "średnia", "niska"))
ocena

[1] niska   średnia wysoka  średnia niska
Levels: niska średnia wysoka

Dopuszczalne wartości określone są w polu **levels**.  Można  określić również poziomy, które nie wystąpiły we wczytanych danych.

In [57]:
levels(ocena)

[1] "niska"   "średnia" "wysoka"

In [59]:
ocena <- factor(c("niska", "średnia", "wysoka", "średnia", "niska"), levels=c("niska", "średnia", "wysoka","bardzo wysoka"))
ocena

[1] niska   średnia wysoka  średnia niska
Levels: niska średnia wysoka bardzo wysoka

In [61]:
levels(ocena)

[1] "niska"         "średnia"       "wysoka"        "bardzo wysoka"

Podsumowanie informacji zawartych w tej zmiennej możemy odczytać funkcją `str`.

In [62]:
str(ocena)

 Factor w/ 4 levels "niska","średnia",..: 1 2 3 2 1

Informację o częstości każdego levelu można odczytać funkcją `table`.

In [63]:
table(ocena)

ocena
        niska       średnia        wysoka bardzo wysoka
            2             2             1             0

O ile zawsze wartością przy porządkowe są "techniczne" inty, to możemy wymusić by system uwzględniał relację między nimi, czyli wiedział które wartości mają być interpretowane jako większe od innych.

In [64]:
ocena_ord <- factor(
  c("niska", "średnia", "wysoka"),
  levels = c("niska", "średnia", "wysoka"),
  ordered = TRUE
)

ocena_ord

[1] niska   średnia wysoka
Levels: niska < średnia < wysoka

In [65]:
#Dla danych uporządkowanych - wartość boolowa
ocena_ord[1] < ocena_ord[2]

[1] TRUE

In [66]:
#Dla danych nieuporządkowanych - ostrzeżenie i NA
ocena[1] < ocena[2]

Warning message in Ops.factor(ocena[1], ocena[2]):
"'<' nie ma sensu dla czynników"

[1] NA

<h3>data.frame</h3>

Wróćmy do typu `data.frame`. Najczęściej będzie on zawierał różne typy danych.

In [67]:
# Integer
wiek <- c(25L, 30L, 22L, 28L)

# Double (numeric)
wzrost <- c(175.5, 180.2, 165.0, 170.8)

# Character
imie <- c("Anna", "Bartek", "Cezary", "Dorota")

# Factor (kategoria)
plec <- factor(c("K", "M", "M", "K"))

In [68]:
dane <- data.frame(
  imie = imie,
  wiek = wiek,
  wzrost = wzrost,
  plec = plec
)

dane

  imie   wiek wzrost plec
1 Anna   25   175.5  K
2 Bartek 30   180.2  M
3 Cezary 22   165.0  M
4 Dorota 28   170.8  K

Jak widzimy, tworząc obiekt w ten sposób utworzyliśmy od razu nazwy kolumn. Możemy się do nich odwołać korzystając z funkcji `colnames`.

In [69]:
colnames(dane)

[1] "imie"   "wiek"   "wzrost" "plec"

Wówczas do konkretnych kolumn możemy się odwoływać po ich nagłówkach.

In [70]:
dane['wiek']

  wiek
1 25
2 30
3 22
4 28

Alternatywnie możemy również odwołać się wpisując nazwę kolumny po znaku dolara $.

In [71]:
dane$wiek

[1] 25 30 22 28

Albo po indeksie

In [72]:
dane[,1]

[1] "Anna"   "Bartek" "Cezary" "Dorota"

Możemy również w każdym momencie zmienić ich nazwy.

In [73]:
colnames(dane) = c('V1', 'V2', 'V3', 'V4')
dane

  V1     V2 V3    V4
1 Anna   25 175.5 K
2 Bartek 30 180.2 M
3 Cezary 22 165.0 M
4 Dorota 28 170.8 K

Możemy również filtrować wiersze po warunku z użyciem funkcji `subset`.

In [74]:
subset(dane, V4=='M')

  V1     V2 V3    V4
2 Bartek 30 180.2 M
3 Cezary 22 165.0 M

Zadanie:

Wczytaj dane z plików i połącz je jedną zmienną `data.frame`. Wypisz podstawowe informacje tego obiektu.

In [ ]:
{}

<h2>Pętle</h2>

Zanim przejdziemy do pętli zauważmy, że nauczyliśmy już się tworzyć proste sekwencje wartości przy pomocy `:`.

In [75]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

Operacja ta będzie działała również w przypadku liczy zmiennoprzecinkowych.

In [76]:
1.2:10.5

 [1]  1.2  2.2  3.2  4.2  5.2  6.2  7.2  8.2  9.2 10.2

Jeśli jednak chcemy zachować odstęp inny niż `1`, to powinniśmy użyć funkcji `seq`.

In [77]:
sekwencja = seq(1, 10, 0.2)
sekwencja

 [1]  1.0  1.2  1.4  1.6  1.8  2.0  2.2  2.4  2.6  2.8  3.0  3.2  3.4  3.6  3.8
[16]  4.0  4.2  4.4  4.6  4.8  5.0  5.2  5.4  5.6  5.8  6.0  6.2  6.4  6.6  6.8
[31]  7.0  7.2  7.4  7.6  7.8  8.0  8.2  8.4  8.6  8.8  9.0  9.2  9.4  9.6  9.8
[46] 10.0

W **R** istnieją trzy podstawowe pętle: `for`, `while` i `repeat`, a ich budowa nie różni się zasadniczo od tych znanych z innych języków.

In [78]:
for(i in sekwencja) {
    print(i)}

[1] 1
[1] 1.2
[1] 1.4
[1] 1.6
[1] 1.8
[1] 2
[1] 2.2
[1] 2.4
[1] 2.6
[1] 2.8
[1] 3
[1] 3.2
[1] 3.4
[1] 3.6
[1] 3.8
[1] 4
[1] 4.2
[1] 4.4
[1] 4.6
[1] 4.8
[1] 5
[1] 5.2
[1] 5.4
[1] 5.6
[1] 5.8
[1] 6
[1] 6.2
[1] 6.4
[1] 6.6
[1] 6.8
[1] 7
[1] 7.2
[1] 7.4
[1] 7.6
[1] 7.8
[1] 8
[1] 8.2
[1] 8.4
[1] 8.6
[1] 8.8
[1] 9
[1] 9.2
[1] 9.4
[1] 9.6
[1] 9.8
[1] 10

In [79]:
i=1
while(sekwencja[i] < 9) {
    print(sekwencja[i])
    i=i+1}

[1] 1
[1] 1.2
[1] 1.4
[1] 1.6
[1] 1.8
[1] 2
[1] 2.2
[1] 2.4
[1] 2.6
[1] 2.8
[1] 3
[1] 3.2
[1] 3.4
[1] 3.6
[1] 3.8
[1] 4
[1] 4.2
[1] 4.4
[1] 4.6
[1] 4.8
[1] 5
[1] 5.2
[1] 5.4
[1] 5.6
[1] 5.8
[1] 6
[1] 6.2
[1] 6.4
[1] 6.6
[1] 6.8
[1] 7
[1] 7.2
[1] 7.4
[1] 7.6
[1] 7.8
[1] 8
[1] 8.2
[1] 8.4
[1] 8.6
[1] 8.8

In [80]:
i=1
repeat {
  print(sekwencja[i])
  i = i+1
  if(sekwencja[i]>5) {
    break
  }
}

[1] 1
[1] 1.2
[1] 1.4
[1] 1.6
[1] 1.8
[1] 2
[1] 2.2
[1] 2.4
[1] 2.6
[1] 2.8
[1] 3
[1] 3.2
[1] 3.4
[1] 3.6
[1] 3.8
[1] 4
[1] 4.2
[1] 4.4
[1] 4.6
[1] 4.8
[1] 5

Przy okazji zauważyliśmy, że działa komenda `break`. Podobnie działa również `continue`. 

Uwaga!

Jeżeli chcemy stworzyć pętlę `for` po indeksach to używamy :`.

In [81]:
for (i in 1:length(sekwencja)) {
    print(sekwencja[i])
}

[1] 1
[1] 1.2
[1] 1.4
[1] 1.6
[1] 1.8
[1] 2
[1] 2.2
[1] 2.4
[1] 2.6
[1] 2.8
[1] 3
[1] 3.2
[1] 3.4
[1] 3.6
[1] 3.8
[1] 4
[1] 4.2
[1] 4.4
[1] 4.6
[1] 4.8
[1] 5
[1] 5.2
[1] 5.4
[1] 5.6
[1] 5.8
[1] 6
[1] 6.2
[1] 6.4
[1] 6.6
[1] 6.8
[1] 7
[1] 7.2
[1] 7.4
[1] 7.6
[1] 7.8
[1] 8
[1] 8.2
[1] 8.4
[1] 8.6
[1] 8.8
[1] 9
[1] 9.2
[1] 9.4
[1] 9.6
[1] 9.8
[1] 10

<h2>Instrukcje warunkowe</h2>

**R** dostarcza dwa dwie podstawowe instrukcje warunkowe `if` oraz `switch`.

In [82]:
x = 0
if (x < 0) {
  print("liczba ujemna")
} else if (x > 0) {
  print("liczba dodatnia")
} else
  print("zero")

[1] "zero"

Warto może zwrócić uwagę na sprawdzanie typów zmiennych. Do tego celu służą komendy `is.integer`, `id.double`, itp.

In [83]:
x = 30L
if (is.integer(x))
{
  print("X to Int")
}

[1] "X to Int"

Podobie do rzutowania zmiennych istnieją funkcje typu `as.integer`, `as.double`, itp.

In [84]:
x = 30
if (is.integer(x))
{
  print("X to Int")
} else
{
  print("X to nie jest Int")    
}
x = as.integer(x)
if (is.integer(x))
{
  print("Już jest intem")
}

[1] "X to nie jest Int"
[1] "Już jest intem"

Może wyszukiwać wartości w listach korzystając z `%in%`.

In [86]:
x = c("jeden","dwa","trzy")

if("dwa" %in% x) {
  print("Znaleziono")
} else {
  print("Brak")
}

[1] "Znaleziono"

Instrukcja `switch` służy do wyboru jednej z kilku opcji. Instrukcja nie przechodzi do kolejnych poniżej.

`switch(EXPR,`

`    name1 = value1,`

`    name2 = value2,`

`    name3 = value3)`

In [85]:
switch(
  1,
  "first",
  "second",
  "third",
  "fourth"
)

[1] "first"

In [87]:
operacja <- "pomnoz"

wynik <- switch(operacja,
                dodaj = 2 + 2,
                odejmij = 2 - 2,
                pomnoz = 2 * 2,
                "Nieznana operacja")
wynik

[1] 4

In [88]:
#wartość domyślna
operacja <- "poteguj"

wynik <- switch(operacja,
                dodaj = 2 + 2,
                odejmij = 2 - 2,
                pomnoz = 2 * 2,
                "Nieznana operacja")
wynik

[1] "Nieznana operacja"

Korzystanie ze zmiennych

In [ ]:
x <- 16
fun <- "sqrt"

wynik <- switch(fun,
                sqrt = sqrt,
                log = log,
                exp = exp)(x)
wynik

<h2>Funkcje</h2>

Funkcję przypisujemy do zmiennej. Tworzymy ją wyrażeniem `function`.

In [89]:
# Tworzenie funkcji
new.function <- function(a) {
  for(i in 1:a) {
    b <- i^2
    print(b)
  }
}

In [90]:
# wywołanie funkcji
new.function(6)

[1] 1
[1] 4
[1] 9
[1] 16
[1] 25
[1] 36

Możemy w różny sposób korzystać z parametrów.

In [91]:
# funkcja bez parametru
new.function <- function() {
  for(i in 1:5) {
    print(i^2)
  }
}

In [92]:
# wywołanie
new.function()

[1] 1
[1] 4
[1] 9
[1] 16
[1] 25

In [93]:
# funkcja z parametrami
new.function <- function(a,b,c) {
  result <- a * b + c
  print(result)
}

In [94]:
# parametry podane pozycyjnie
new.function(5,3,11)

[1] 26

In [95]:
# parametry podane z nazwami
new.function(a = 11, b = 5, c = 3)

[1] 58

In [96]:
# utworzenie funkcji z parametrami ze zdefiniowanymi wartościami domyślnymi
new.function <- function(a = 3, b = 6) {
  result <- a * b
  print(result)
}

In [98]:
new.function()

[1] 18

In [97]:
new.function(9,5)

[1] 45

Uwaga! 

Parametr jest sprawdzany dopiero wtedy, kiedy ma być użyty.

In [99]:
new.function <- function(a, b) {
  print(a^2)
  print(a)
  print(b)
}

In [100]:
# wywołanie funkcji bez jednego parametru.
new.function(6)

[1] 36
[1] 6

ERROR: Error in new.function(6): brakuje argumentu 'b', a nie ma określonej wartości domyślnej